### ISSUE TITLE
String Validators

### ISSUE THREAD

**Issue by rphilip457** [jTaylo99/kolumnextractor#1]
- Lower Case
- Upper
- Camel
- Normalised

**Comment by jTaylo99** [comment]
This could be done in 2 pull requests. Each handling 2 validators each.

**Comment by ThisisMS11** [comment]
Please assign this issue to me.

**Comment by jTaylo99** [comment]
For an example of a validator, there is the Number validator in validation.py. The idea would be that there would be separate validators per use case (eg. lower_case_str_validator, upper_case_str_validator) etc.
