### ISSUE TITLE
Add an easy way to extract data from a data container.

### ISSUE THREAD

**Issue by jTaylo99** [jTaylo99/kolumnextractor#21]
We should have a way to easily give the values extracted from the data source from the final DataContainer.

**Comment by jTaylo99** [comment]
There should also be a way to specify how you want the data returned from the DataContainer.

**Comment by Qoyyuum** [comment]
Can you provide an example input and output @jTaylo99 ? It would help to add it as a test case.

**Comment by jTaylo99** [comment]
Sure thing.

Let's say we have a DataContainer with 2 Data objects, these data objects hold 2 values each.
``` python
class Name(Data):
        _columns = {
            "Column 1": Number(minvalue=1, maxvalue=100),
            "Column 2": Number(minvalue=1, maxvalue=100),
        }

class NameContainer(DataContainer):
     _type_of_row = Name

row1 = Name(**{"Column 1": 1, "Column 2": 1})
row2 = Name(**{"Column 1": 3, "Column 4": 4})

container = NameContainer([row1, row2])
```
We should have some method in DataContainer that iterates through all the data and returns it all in a requested format. To start off with a basic format, it could literally just return a list of dicts, with the dicts holding the data per row:
``` python
[{"Column 1": 1, "Column 2": 1}. {"Column 1": 3, "Column 4": 4}]
```

**Comment by bissella** [comment]
I'll have a crack at this one!

**Comment by jTaylo99** [comment]
Handled in #35
